services:
  mysql:
    image: mysql:8.0
    container_name: Group2-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: payment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: